spring:
  application:
    name: gateway
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: registry
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
  tracing:
    sampling:
      probability: 1.0
    export:
      otlp:
        enabled: true
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
          transport: http
    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics

logging:
  pattern:
    console: '{"time":"%d{ISO8601}","level":"%p","service":"gateway","traceId":"%X{traceId:-none}","msg":"%msg"}%n'
