/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.5.0/samples
 */

import net.ltgt.gradle.errorprone.errorprone
import org.gradle.api.plugins.quality.CheckstyleExtension
import org.gradle.api.tasks.testing.logging.TestLogEvent
import io.spring.gradle.dependencymanagement.dsl.DependencyManagementExtension

plugins {
    id("org.springframework.boot") apply false
    id("io.spring.dependency-management") version "1.1.7" apply false
    id("com.diffplug.spotless") version "7.0.2" apply false
    id("net.ltgt.errorprone") version "4.1.0" apply false
    java
}

val springBootVersion: String by project
val springCloudVersion: String by project
val testcontainersVersion: String by project
val javaVersion: String by project

subprojects {
    apply(plugin = "java")
    apply(plugin = "io.spring.dependency-management")
    apply(plugin = "com.diffplug.spotless")
    apply(plugin = "net.ltgt.errorprone")
    apply(plugin = "checkstyle")

    // Import hygiene only — no full reformat. `check`/`build` run spotlessCheck automatically.
    configure<com.diffplug.gradle.spotless.SpotlessExtension> {
        java {
            target("src/main/java/**/*.java", "src/test/java/**/*.java")
            removeUnusedImports()
            trimTrailingWhitespace()
            endWithNewline()
        }
    }

    configure<CheckstyleExtension> {
        configFile = rootProject.file("config/checkstyle/checkstyle.xml")
        toolVersion = "10.21.0"
    }

    group = "io.cartogra"
    version = "0.1.0-SNAPSHOT"

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(javaVersion.toInt())
        }
    }

    extensions.configure<DependencyManagementExtension> {
        imports {
            mavenBom("org.springframework.boot:spring-boot-dependencies:$springBootVersion")
            mavenBom("org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion")
            mavenBom("org.testcontainers:testcontainers-bom:$testcontainersVersion")
        }
        dependencies {
            // CVE overrides not yet covered by spring-boot-dependencies:$springBootVersion — recheck on next BOM bump
            dependency("org.postgresql:postgresql:42.7.11") // CVE-2026-42198
            dependency("org.springframework.kafka:spring-kafka:4.0.6") // CVE-2026-41731
            dependency("org.apache.tomcat.embed:tomcat-embed-core:11.0.22") // CVE-2026-41293
            dependency("org.apache.tomcat.embed:tomcat-embed-el:11.0.22")
            dependency("org.apache.tomcat.embed:tomcat-embed-websocket:11.0.22")
            dependency("com.fasterxml.jackson.core:jackson-databind:2.21.4") // CVE-2026-54512, CVE-2026-54513
            dependency("tools.jackson.core:jackson-databind:3.1.4") // CVE-2026-54512, CVE-2026-54513
        }
    }

    repositories {
        mavenCentral()
        maven { url = uri("https://repo.spring.io/milestone") }
    }

    dependencies {
        "errorprone"("com.google.errorprone:error_prone_core:2.36.0")
    }

    tasks.withType<JavaCompile> {
        options.encoding = "UTF-8"
        options.compilerArgs.addAll(listOf(
            "-parameters",
            "-Xlint:deprecation",
            "-Xlint:unchecked",
        ))
        options.errorprone {
            error("UnusedVariable")
            // fire-and-forget Kafka sends are intentional
            disable("FutureReturnValueIgnored")
            // Optional.orElseThrow() used for side-effect (existence check before delete)
            disable("ReturnValueIgnored")
            // split("\\s+") on controlled config input is fine
            disable("StringSplitter")
        }
    }

    tasks.withType<Test> {
        useJUnitPlatform()
        testLogging { events(TestLogEvent.PASSED, TestLogEvent.FAILED, TestLogEvent.SKIPPED) }
    }
}
