/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.5.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    val springBootVersion: String by settings

    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = uri("https://repo.spring.io/milestone") }
    }

    plugins {
        id("org.springframework.boot") version springBootVersion
    }
}

rootProject.name = "cartogra"

include(
    "shared:common",
    "shared:test-support",
    "services:gateway",
    "services:registry",
    "services:ingestion",
    "services:topology"
)
