tempo:
  image:
    repository: grafana/tempo
    tag: "2.7.1"

  replicas: 1

  persistence:
    enabled: true
    size: 20Gi

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi

  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    fsGroup: 10001
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]

  config:
    compactor:
      compaction:
        block_retention: 720h
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/blocks
        wal:
          path: /var/tempo/wal
    metrics_generator:
      enabled: true
      registry:
        external_labels:
          source: tempo
          cluster: production
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://kube-prometheus-stack-prometheus.infra.svc.cluster.local:9090/api/v1/write
            send_exemplars: true
    overrides:
      defaults:
        metrics_generator:
          processors: [service-graphs, span-metrics]
          generate_native_histograms: both

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack
